version: '2.1'
orbs:
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/buildpack-deps:stretch
    environment:
      IMAGE_NAME: juice-shop/juice-shop
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
workflows: null
